openapi: 3.1.0

# ASAM SOVD V1.0.0

# © by ASAM e.V., 2022

# SOVD API Parameter Definitions for configurations resource
# This file is informative. The normative REST API definition is published in the specification.


# Any use is limited to the scope described in the ASAM license terms. 
# See http://www.asam.net/license.html  for further details.

info:
  title: SOVD API Parameter Definitions for configurations resource
  license: 
    name: Licensing Terms for Grant of Rights to Use ASAM Products
    url: https://www.asam.net/license/
  version: 1.0.0
  description: >-
    Common parameter definitions for configurations resource

paths: {}

components:
  parameters:
    # ------------------------------------------------------------------------
    ConfigurationId:
      name: configuration-id
      description: >-
        The identifier for the configuration
      in: path
      required: true
      schema:
        type: string
