openapi: 3.1.0

# ASAM SOVD V1.0.0

# © by ASAM e.V., 2022

# SOVD API for Authentication
# This file is informative. The normative REST API definition is published in the specification.


# Any use is limited to the scope described in the ASAM license terms.
# See http://www.asam.net/license.html  for further details.

info:
  title: SOVD API for Authentication
  license:
    name: Licensing Terms for Grant of Rights to Use ASAM Products
    url: https://www.asam.net/license/
  version: 1.0.0

paths:

  # ------------------------------------------------------------------------
  /authorize:
    post:
      description: >-
        This method initiates an authorization flow to authenticate and authorize
        an SOVD client to act upon a human user. Depending on the actual flow type,
        the result of this flow is an authorization code, that the client can use
        to obtain a token using a subsequent call to the /token API method, or an
        access token. This method is only used in the context of human user interaction.
      requestBody:
        description: >-
          The request body depends on the selected authorization protocol
          and its implementation by the SOVD API.
        content:
          '*/*':
            schema:
              $ref: ../commons/types.yaml#/components/schemas/AnyValue
      responses:
        "200":
          description: >-
            The request was successful.
            The response body depends on the selected authorization protocol
            and its implementation by the SOVD API.
        "400":
          description: The SOVD client credentials are not provided as part of the request.
          $ref: ../commons/responses.yaml#/components/responses/GenericError
        default:
          $ref: ../commons/responses.yaml#/components/responses/GenericError

  # ------------------------------------------------------------------------
  /token:
    post:
      description: >-
        The SOVD client can request a token via this method. The AuthorizationServer
        shall accept requests to create tokens from authenticated SOVD clients only.
        Therefore, an SOVD client shall authenticate against the AuthorizationServer
        or have some other credentials to proof its identity prior a token is created
        and returned via the SOVD API. An SOVD client, which cannot be authorized shall
        not be able to request a token through the SOVD API. Traditional methods like
        client-id / client-secret combinations can be used, as well as advanced methods
        for instance, based on client certificates.
      requestBody:
        description: >-
          The request body depends on the selected authorization protocol
          and its implementation by the SOVD API.
        content:
          '*/*':
            schema:
              $ref: ../commons/types.yaml#/components/schemas/AnyValue
              examples:
                - "grant_type=client_credentials"
      responses:
        "200":
          description: >-
            The request was successful.
            The response body depends on the selected authorization protocol
            and its implementation by the SOVD API.
          content:
            '*/*':
              schema:
                $ref: ../commons/types.yaml#/components/schemas/AnyValue
                example: >-
                    {
                    "access_token":"eyJ0eXAiOiJKV1QiLA0KICJhbGciOiJIUzI1NiJ9.
                    eyJpc3MiOiJqb2UiLA0KICJleHAiOjEzMDA4MTkzODAsDQogImh0dHA6Ly9leGFtcGxlLmNvbS9pc19yb290Ijp0cnVlfQ.
                    dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk",
                    "token_type":"Bearer",
                    "expires_in":3600
                    }
        "400":
          description: >-
            If the challenge was not responded to correctly or something else
            is missing or is invalid (request, client-id, etc.)
          $ref: ../commons/responses.yaml#/components/responses/GenericError
        default:
          $ref: ../commons/responses.yaml#/components/responses/GenericError
